# SSOT Redirect

このファイルは SSOT 原則に基づき移動されました。

**正規ソース**: [.system_core/Configuration/auto_cleanup_config.yaml](.system_core/Configuration/auto_cleanup_config.yaml)

**移動理由**: 重複ファイル解決
**移動日時**: 2025-05-31T05:43:38.846134

このリダイレクトファイルは自動生成されました。
内容は正規ソースを参照してください。
